version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres     # Логин Hibernate
      POSTGRES_PASSWORD: root     # Пароль
      POSTGRES_DB: postgres       # Название БД Hibernate
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: